import { NextApiResponse } from 'next';
import { createSessionClient } from '@/lib/appwrite';
import { ID, Query } from 'appwrite';
import { withAuth, AuthenticatedRequest } from '@/lib/apiMiddleware';
import { shouldLog } from '@/lib/logSettings';

/**
 * Attendee Duplicate API Endpoint
 *
 * POST /api/attendees/duplicate
 * Body: { attendeeId: string }
 *
 * Duplicates an attendee record, copying all fields except:
 * - photo (cleared — new photo required)
 * - barcode (a new unique barcode is generated by the caller and passed in)
 * - credential fields (credentialUrl, credentialGeneratedAt, lastSignificantUpdate)
 *
 * The caller must pass a pre-generated unique barcode in the request body.
 * Requires attendees.duplicate permission.
 */
export default withAuth(async (req: AuthenticatedRequest, res: NextApiResponse) => {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { user, userProfile } = req;
  const { tablesDB } = createSessionClient(req);

  const dbId = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
  const attendeesTableId = process.env.NEXT_PUBLIC_APPWRITE_ATTENDEES_TABLE_ID!;
  const logsTableId = process.env.NEXT_PUBLIC_APPWRITE_LOGS_TABLE_ID!;
  const accessControlTableId = process.env.NEXT_PUBLIC_APPWRITE_ACCESS_CONTROL_TABLE_ID;

  // Check permission
  const permissions = userProfile.role ? userProfile.role.permissions : {};
  const hasDuplicatePermission =
    permissions?.attendees?.duplicate === true || permissions?.all === true;

  if (!hasDuplicatePermission) {
    return res.status(403).json({ error: 'Insufficient permissions to duplicate attendees' });
  }

  const { attendeeId, newBarcodeNumber } = req.body;

  if (!attendeeId || typeof attendeeId !== 'string') {
    return res.status(400).json({ error: 'attendeeId is required' });
  }

  if (!newBarcodeNumber || typeof newBarcodeNumber !== 'string') {
    return res.status(400).json({ error: 'newBarcodeNumber is required' });
  }

  try {
    // Fetch the source attendee
    const source = await tablesDB.getRow({
      databaseId: dbId,
      tableId: attendeesTableId,
      rowId: attendeeId,
    });

    if (!source) {
      return res.status(404).json({ error: 'Attendee not found' });
    }

    // Check for barcode uniqueness before creation (prevent TOCTOU race)
    const barcodeCheckResult = await tablesDB.listRows({
      databaseId: dbId,
      tableId: attendeesTableId,
      queries: [Query.equal('barcodeNumber', newBarcodeNumber), Query.limit(1)],
    });

    if (barcodeCheckResult.rows.length > 0) {
      return res.status(409).json({ error: 'Barcode number already exists' });
    }

    // Build the duplicate data — clear photo and credential fields, use new barcode
    const duplicateData: Record<string, unknown> = {
      firstName: source.firstName || '',
      lastName: source.lastName || '',
      barcodeNumber: newBarcodeNumber,
      notes: source.notes || '',
      photoUrl: null,
      customFieldValues: source.customFieldValues || null,
      // Clear credential fields — the duplicate starts fresh
      credentialUrl: null,
      credentialGeneratedAt: null,
      lastSignificantUpdate: new Date().toISOString(),
    };

    // Create the duplicate row with error handling for unique constraint violations
    let newRow;
    try {
      newRow = await tablesDB.createRow({
        databaseId: dbId,
        tableId: attendeesTableId,
        rowId: ID.unique(),
        data: duplicateData,
      });
    } catch (createError: any) {
      // Handle database unique constraint errors
      if (
        createError.code === 'UNIQUE_CONSTRAINT_VIOLATION' ||
        createError.message?.includes('unique') ||
        createError.message?.includes('duplicate')
      ) {
        console.error('[Duplicate] Unique constraint violation on barcode:', {
          barcodeNumber: newBarcodeNumber,
          error: createError.message,
        });
        return res.status(409).json({ error: 'Barcode number already exists' });
      }
      // Re-throw other database errors
      throw createError;
    }

    // Copy access control from source attendee
    if (accessControlTableId) {
      try {
        // Fetch source attendee's access control record
        const sourceAcResult = await tablesDB.listRows({
          databaseId: dbId,
          tableId: accessControlTableId,
          queries: [Query.equal('attendeeId', attendeeId), Query.limit(1)],
        });

        const sourceAc = sourceAcResult.rows[0];
        await tablesDB.createRow({
          databaseId: dbId,
          tableId: accessControlTableId,
          rowId: ID.unique(),
          data: {
            attendeeId: newRow.$id,
            accessEnabled: sourceAc?.accessEnabled ?? true,
            validFrom: sourceAc?.validFrom ?? null,
            validUntil: sourceAc?.validUntil ?? null,
          },
        });
      } catch (acError) {
        // Non-fatal — continue without access control record
        console.warn('[Duplicate] Failed to create access control record:', acError);
      }
    }

    // Log the duplication
    if (await shouldLog('attendeeDuplicate')) {
      try {
        await tablesDB.createRow({
          databaseId: dbId,
          tableId: logsTableId,
          rowId: ID.unique(),
          data: {
            action: 'attendee_duplicated',
            userId: user.$id,
            details: JSON.stringify({
              sourceAttendeeId: attendeeId,
              newAttendeeId: newRow.$id,
              firstName: source.firstName,
              lastName: source.lastName,
            }),
            timestamp: new Date().toISOString(),
          },
        });
      } catch (logError) {
        console.warn('[Duplicate] Failed to write log:', logError);
      }
    }

    return res.status(201).json({
      id: newRow.$id,
      ...duplicateData,
    });
  } catch (error: any) {
    console.error('[Duplicate] Error duplicating attendee:', error);
    return res.status(500).json({ error: error.message || 'Failed to duplicate attendee' });
  }
});
